# Generated by Django 5.0.2 on 2024-03-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('Chapter', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('Established', models.CharField(max_length=20)),
            ],
        ),
    ]
